name: Build

permissions:
    contents: write

on:
    push:
        branches: [main]

jobs:
    build:
        name: Build MacOS-x64 / MacOS-arm64
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: 18

            - run: npm install
            - run: npm install pkg

            - name: Build Launcher (MacOS-x64)
              shell: bash
              run: |
                npx pkg . --targets node18-macos-x64 --output dist/Launcher-MACOS-x64
                npx pkg . --targets node18-macos-arm64 --output dist/Launcher-MACOS-arm64
            
            - uses: actions/upload-artifact@v4
              with:
                name: Launcher-Artifact-MacOS
                path: dist/
            
            - name: Commit Launchers (MacOS)
              run: |
                git config user.name "github-actions[bot]"
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                git add dist/Launcher-MACOS-x64
                git add dist/Launcher-MACOS-arm64

                git commit -m "Update Launchers (MacOS)" || echo "No changes; not commiting build."
                git push
